"""app.py'den cikarildi, adim 1 -- i18n metin sozlukleri, saf veri, yan etki yok."""

# ADS-B/Mode-S emitter kategori kodlari (standart, ilk harf sinif, rakam alt tip)
# Dil destegi icin TR/EN ayri sozlukler -- CATEGORY_LABELS[lang][kod] seklinde kullanilir.
CATEGORY_LABELS = {
    "tr": {
        "A0": "Bilinmiyor", "A1": "Hafif uçak", "A2": "Küçük uçak",
        "A3": "Büyük uçak", "A4": "Büyük uçak (yüksek vorteks)", "A5": "Ağır uçak",
        "A6": "Yüksek performans", "A7": "Helikopter",
        "B0": "Bilinmiyor", "B1": "Planör", "B2": "Balon/Zeplin",
        "B3": "Paraşütçü", "B4": "Ultralight/Yamaç paraşütü",
        "B6": "İHA/Drone", "B7": "Uzay aracı",
        "C0": "Bilinmiyor", "C1": "Yer taşıtı (acil)", "C2": "Yer taşıtı (servis)",
        "C3": "Sabit engel", "C4": "Engel kümesi", "C5": "Hat engeli",
    },
    "en": {
        "A0": "Unknown", "A1": "Light aircraft", "A2": "Small aircraft",
        "A3": "Large aircraft", "A4": "Large aircraft (high vortex)", "A5": "Heavy aircraft",
        "A6": "High performance", "A7": "Helicopter",
        "B0": "Unknown", "B1": "Glider", "B2": "Balloon/Airship",
        "B3": "Parachutist", "B4": "Ultralight/Paraglider",
        "B6": "UAV/Drone", "B7": "Spacecraft",
        "C0": "Unknown", "C1": "Ground vehicle (emergency)", "C2": "Ground vehicle (service)",
        "C3": "Fixed obstacle", "C4": "Cluster obstacle", "C5": "Line obstacle",
    },
}

# ADS-B acil durum kodlari (Mode S emergency/priority status)
EMERGENCY_LABELS = {
    "tr": {
        "none": None,  # normal durum, gosterme
        "general": "GENEL ACİL DURUM",
        "lifeguard": "SAĞLIK ACİL DURUMU",
        "minfuel": "YAKIT KRİTİK",
        "nordo": "RADYO ARIZASI",
        "unlawful": "KAÇIRMA (HİJACK)",
        "downed": "DÜŞTÜ/İNİŞ ZORUNLU",
        "reserved": "REZERVE KOD",
    },
    "en": {
        "none": None,
        "general": "GENERAL EMERGENCY",
        "lifeguard": "MEDICAL EMERGENCY",
        "minfuel": "FUEL CRITICAL",
        "nordo": "RADIO FAILURE",
        "unlawful": "HIJACKING",
        "downed": "DOWNED / FORCED LANDING",
        "reserved": "RESERVED CODE",
    },
}

DEFAULT_LANGUAGE = "tr"

# Arayuzdeki tum sabit/dinamik metinler -- TEXTS[lang]["anahtar"] seklinde
# kullanilir. Yeni bir dil eklemek icin buraya ucuncu bir blok (orn. "de")
# eklemek yeterli, kodun geri kalani degismeden calisir.
TEXTS = {
    "tr": {
        "settings_title": "Ayarlar",
        "timezone_label": "Saat dilimi (UTC farkı)",
        "language_label": "Dil",
        "aircraft_info_title": "Uçak Bilgisi",
        "history_panel_title": "Geçmiş",
        "history_range_placeholder_start": "Başlangıç",
        "history_range_placeholder_end": "Bitiş",
        "history_day_placeholder": "Gün",
        "history_hour_placeholder": "Saat",
        "history_calculate_label": "Hesapla",
        "callsign_search_placeholder": "Çağrı kodu ara...",
        "callsign_not_found": "'{callsign}' bulunamadı",
        "stats_title": "İstatistikler",
        "stats_yaxis_label": "Benzersiz uçak sayısı",
        "emergency_panel_title": "Acil Durumlar",
        "no_emergency": "Aktif acil durum yok",
        "replay_panel_title": "Tekrar Oynatma",
        "replay_load_label": "Yükle",
        "replay_no_data": "⚠ Bu aralıkta veri bulunamadı — tarih/saat seçili mi?",
        "replay_loaded_label": "✓ {n} kare yüklendi — ▶ ile başlat",
        "replay_live_label": "Canlıya Dön",
        "altitude_legend_title": "İRTİFA (m)",
        "data_source_label": "Veri Kaynağı",
        "data_source_active": "Aktif: {source}",
        "data_source_pending": "İsteniyor: {requested} · aktif: {active} (geçiş bekleniyor)",
        "previous_flights_title": "Önceki Uçuşlar (7 gün)",
        "no_previous_flights": "Bu uçak için geçmiş uçuş bulunamadı.",
        "flight_duration_min": "{min} dk",
        "click_aircraft": "Haritada bir uçağa tıklayın.",
        "no_signal": "{icao} şu anda sinyal göndermiyor (kapsama alanından çıkmış olabilir).",
        "no_callsign": "Çağrı kodu yok, rota sorgulanamıyor.",
        "route_not_found": "'{callsign}' için rota bilgisi bulunamadı (adsbdb.com veritabanında yok).",
        "aircraft_info_not_found": "Uçak tipi/tescil bilgisi bulunamadı.",
        "no_details": "Detay yok",
        "registration": "Tescil",
        "field_icao": "ICAO24",
        "field_callsign": "Çağrı Kodu",
        "field_lat": "Enlem",
        "field_lon": "Boylam",
        "field_alt": "İrtifa",
        "field_speed": "Hız",
        "field_track": "Yön",
        "field_vspeed": "Dikey Hız",
        "field_category": "Kategori",
        "field_squawk": "Squawk",
        "field_last_update": "Son Güncelleme",
        "emergency_squawk": "ACİL DURUM SQUAWK: {squawk}",
        "status_bar_main": "{n} aktif uçuş",
        "status_bar_alarm": " | {a} alarm",
        "history_alt_label": "İrtifa (m)",
        "history_speed_label": "Hız (m/s)",
        "no_data": "Veri bulunamadı",
        "tooltip_alt": "İrtifa",
        "tooltip_speed": "Hız",
        "tooltip_track": "Yön",
        "tooltip_vspeed": "Dikey",
        "tooltip_signal_age": "Sinyal yaşı",
        "tz_default_suffix": " (Türkiye)",
        "filter_civil_label": "Sivil",
        "filter_military_label": "Askeri",
        "filter_ground_label": "Yerde",
        "airline_filter_placeholder": "Firma...",
        "field_military": "Askeri mi",
        "military_yes": "Evet",
        "military_no": "Hayır",
        "field_ground": "Yerde mi",
        "ground_yes": "Evet",
        "ground_no": "Hayır",
        "tooltip_military_tag": "Askeri",
        "tooltip_ground_tag": "Yerde",
        "map_style_label": "Harita Türü",
        "map_style_street": "Sokak",
        "map_style_satellite": "Uydu",
        "map_style_dark": "Karanlık",
        "signal_staleness_label": "Sinyal Yaşı Eşiği",
    },
    "en": {
        "settings_title": "Settings",
        "timezone_label": "Time zone (UTC offset)",
        "language_label": "Language",
        "aircraft_info_title": "Aircraft Info",
        "history_panel_title": "History",
        "history_range_placeholder_start": "Start",
        "history_range_placeholder_end": "End",
        "history_day_placeholder": "Day",
        "history_hour_placeholder": "Hour",
        "history_calculate_label": "Calculate",
        "callsign_search_placeholder": "Search callsign...",
        "callsign_not_found": "'{callsign}' not found",
        "stats_title": "Statistics",
        "stats_yaxis_label": "Unique aircraft count",
        "emergency_panel_title": "Emergency Alerts",
        "no_emergency": "No active emergencies",
        "replay_panel_title": "Replay",
        "replay_load_label": "Load",
        "replay_no_data": "⚠ No data found in this range — is a date/time selected?",
        "replay_loaded_label": "✓ {n} frames loaded — press ▶ to start",
        "replay_live_label": "Return to Live",
        "altitude_legend_title": "ALTITUDE (m)",
        "data_source_label": "Data Source",
        "data_source_active": "Active: {source}",
        "data_source_pending": "Requested: {requested} · active: {active} (switch pending)",
        "previous_flights_title": "Previous Flights (7 days)",
        "no_previous_flights": "No previous flights found for this aircraft.",
        "flight_duration_min": "{min} min",
        "click_aircraft": "Click an aircraft on the map.",
        "no_signal": "{icao} is not currently transmitting (may have left coverage area).",
        "no_callsign": "No callsign, route lookup unavailable.",
        "route_not_found": "No route found for '{callsign}' (not in the adsbdb.com database).",
        "aircraft_info_not_found": "No aircraft type/registration info found.",
        "no_details": "No details",
        "registration": "Registration",
        "field_icao": "ICAO24",
        "field_callsign": "Callsign",
        "field_lat": "Latitude",
        "field_lon": "Longitude",
        "field_alt": "Altitude",
        "field_speed": "Speed",
        "field_track": "Heading",
        "field_vspeed": "Vertical Speed",
        "field_category": "Category",
        "field_squawk": "Squawk",
        "field_last_update": "Last Update",
        "emergency_squawk": "EMERGENCY SQUAWK: {squawk}",
        "status_bar_main": "{n} active flights",
        "status_bar_alarm": " | {a} alerts",
        "history_alt_label": "Altitude (m)",
        "history_speed_label": "Speed (m/s)",
        "no_data": "No data found",
        "tooltip_alt": "Alt",
        "tooltip_speed": "Speed",
        "tooltip_track": "Heading",
        "tooltip_vspeed": "V/S",
        "tooltip_signal_age": "Signal age",
        "tz_default_suffix": " (Turkey)",
        "filter_civil_label": "Civilian",
        "filter_military_label": "Military",
        "filter_ground_label": "Ground",
        "airline_filter_placeholder": "Airline...",
        "field_military": "Military",
        "military_yes": "Yes",
        "military_no": "No",
        "field_ground": "On Ground",
        "ground_yes": "Yes",
        "ground_no": "No",
        "tooltip_military_tag": "Military",
        "tooltip_ground_tag": "Ground",
        "map_style_label": "Map Style",
        "map_style_street": "Street",
        "map_style_satellite": "Satellite",
        "map_style_dark": "Dark",
        "signal_staleness_label": "Signal Age Threshold",
    },
}
